## **GloVe Vectors**

In [ ]:
import torch
import torchtext

glove = torchtext.vocab.GloVe(name='6B',
                              dim=100)

.vector_cache/glove.6B.zip: 862MB [02:44, 5.23MB/s]                           
100%|█████████▉| 399999/400000 [00:23<00:00, 16896.05it/s]


In [ ]:
glove['cat']

tensor([ 0.2309,  0.2828,  0.6318, -0.5941, -0.5860,  0.6326,  0.2440, -0.1411,
         0.0608, -0.7898, -0.2910,  0.1429,  0.7227,  0.2043,  0.1407,  0.9876,
         0.5253,  0.0975,  0.8822,  0.5122,  0.4020,  0.2117, -0.0131, -0.7162,
         0.5539,  1.1452, -0.8804, -0.5022, -0.2281,  0.0239,  0.1072,  0.0837,
         0.5501,  0.5848,  0.7582,  0.4571, -0.2800,  0.2522,  0.6896, -0.6097,
         0.1958,  0.0442, -0.3114, -0.6883, -0.2272,  0.4618, -0.7716,  0.1021,
         0.5564,  0.0674, -0.5721,  0.2374,  0.4717,  0.8277, -0.2926, -1.3422,
        -0.0993,  0.2814,  0.4160,  0.1058,  0.6220,  0.8950, -0.2345,  0.5135,
         0.9938,  1.1846, -0.1636,  0.2065,  0.7385,  0.2406, -0.9647,  0.1348,
        -0.0072,  0.3302, -0.1236,  0.2719, -0.4095,  0.0219, -0.6069,  0.4076,
         0.1957, -0.4180,  0.1864, -0.0327, -0.7857, -0.1385,  0.0440, -0.0844,
         0.0491,  0.2410,  0.4527, -0.1868,  0.4618,  0.0891, -0.1819, -0.0152,
        -0.7368, -0.1453,  0.1510, -0.71

# **Measuring Distance**

In [ ]:
y = glove['cat']
x = glove['dog']
torch.norm(y - x)

tensor(2.6811)

In [ ]:
x = torch.tensor([1., 1., 1.]).unsqueeze(0)
y = torch.tensor([2., 2., 2.]).unsqueeze(0)
torch.cosine_similarity(x, y) # should be one

tensor([1.0000])

In [ ]:
x

tensor([[1., 1., 1.]])

In [ ]:
x = glove['cat']
y = glove['dog']
torch.cosine_similarity(glove['cat'].unsqueeze(0),
                        glove['dog'].unsqueeze(0))

tensor([0.8798])

Word Similarity

In [ ]:
word = 'cat'
other = ['dog', 'bike', 'kitten', 'puppy', 'kite', 'computer', 'neuron']
for w in other:
    dist = torch.norm(glove[word] - glove[w]) # euclidean distance
    print(w, float(dist))

dog 2.681130886077881
bike 6.0225629806518555
kitten 4.454165935516357
puppy 3.9275598526000977
kite 5.85930061340332
computer 6.960630893707275
neuron 7.568032264709473


In [ ]:
def print_closest_words(vec, n=5):
    dists = torch.norm(glove.vectors - vec, dim=1)     # compute distances to all words
    lst = sorted(enumerate(dists.numpy()), key=lambda x: x[1]) # sort by distance
    for idx, difference in lst[1:n+1]: 					       # take the top n
        print(glove.itos[idx], difference)

print_closest_words(glove["cat"], n=10)

dog 2.681131
rabbit 3.6489704
cats 3.6892002
monkey 3.7469323
puppy 3.9275599
pet 3.9499722
dogs 4.0555873
rat 4.131533
mouse 4.197826
spider 4.2696805


In [ ]:
print_closest_words(glove['computer'])

computers 3.1775317
software 3.711449
technology 4.408793
hardware 4.52742
pc 4.5814285


# **Analogies**

In [ ]:
print_closest_words(glove['queen'] - glove['woman'] + glove['man'])

king 4.081079
prince 5.0347586
royal 5.069449
majesty 5.189214
crown 5.273718
